// This file is auto-generated by @nudge/cli. Do not edit manually.
import { registerPrompts } from "@nudge/core";

declare module "@nudge/core" {
  interface PromptRegistry {
    "summarizer": true;
  }
}

const prompts = {
  "summarizer": {
    text: `# Summarization Task

You are a summarizer. Your task is to summarize the given text concisely and clearly.

**Requirements:**
- Do not add any fluff
- Provide only the essential information
- Keep the summary accurate and direct

Please summarize the following text:`,
    hash: "af79da366690edea",
  }
} as const;

registerPrompts(prompts);
