// This file is auto-generated by @nudge-ai/cli. Do not edit manually.
import { registerPrompts } from "@nudge-ai/core/internal";

declare module "@nudge-ai/core" {
  interface PromptRegistry {
    "concise-rules": true;
    "greeter": true;
    "summarizer": true;
    "test": true;
    "user-router": true;
  }
  interface PromptVariables {
    "greeter": "name" | "topic";
  }
  interface PromptVariants {
    "summarizer": "short" | "detailed";
  }
}

const prompts = {
  "concise-rules": {
    variants: {
      "default": `Use clear, simple language to keep responses concise. Keep it under 3 paragraphs.`,
    },
    hash: "e53c722c626fc02c",
  },
  "greeter": {
    variants: {
      "default": `You are a friendly assistant helping {{name}}.
Value: "the user wants to learn about {{topic}}."
Value: "the user's name and chosen topic."

[Output]
Value: "a personalized greeting message."

[Optional Block End: "introduction"]

[Output]
Value: "start with a warm greeting."

[Optional Block Start: "introduction"]
Value: "Always keep your responses concise. Avoid technical jargon that might confuse users."

[Optional Block End: "introduction"]`,
    },
    hash: "65e97899ef817af1",
  },
  "summarizer": {
    variants: {
      "short": `\`\`\`json
you are an expert summarizer
Value: "Input: text to summarize"
Value: "Output: concise summary"
Value: "Do: preserve key facts and figures"
Value: "Don't: include unnecessary details"
Value: "Do: maintain original meaning"
Value: "Don't: add opinions or interpretations"
Value: "Do: keep it under 3 paragraphs"
\`\`\``,
      "detailed": `You are an expert summarizer. Describe the context and background of the input, and use concise, clear language to summarize the text. Preserve key facts and figures. Use parseable JSON and ensure the output is 3 paragraphs long.`,
    },
    hash: "3504d41e20610093",
  },
  "test": {
    variants: {
      "default": `## Do
- Keep your responses concise and accessible. Avoid technical jargon that might confuse users.
## Test
- First Test
## More
- Keep your responses concise and accessible. Avoid technical jargon that might confuse users.`,
    },
    hash: "9062687584bc45f2",
  },
  "user-router": {
    variants: {
      "default": `You are a web builder editor input router. Interact with the user message.

## Input
User message

## Do
Use clear, simple language

## Don't
Keep it under 3 paragraphs`,
    },
    hash: "e9b6ea2db3bdd38c",
  }
} as const;

registerPrompts(prompts);
