// This file is auto-generated by @nudge-ai/cli. Do not edit manually.
import { registerPrompts } from "@nudge-ai/core/internal";

declare module "@nudge-ai/core" {
  interface PromptRegistry {
    "concise-rules": true;
    "greeter": true;
    "summarizer": true;
    "test": true;
    "user-router": true;
  }
  interface PromptVariables {
    "greeter": "topic";
  }
  interface PromptVariants {
    "summarizer": "short" | "detailed";
  }
}

const prompts = {
  "concise-rules": {
    variants: {
      "default": `Use clear, simple language keep responses concise and accessible. Avoid technical jargon that might confuse users. Keep it under 3 paragraphs.`,
    },
    hash: "e53c722c626fc02c",
  },
  "greeter": {
    variants: {
      "default": `You are a friendly assistant helping the user learn about {{topic}}.

Start with a warm greeting, and address the user by name and focus discussion on their chosen topic.`,
    },
    hash: "65e97899ef817af1",
  },
  "summarizer": {
    variants: {
      "short": `You are an expert summarizer. Describe the input text to be summarized. Help the AI understand the context of what it will be working with, and produce a concise summary of the text. The summary should be 1-2 sentences long.

Preserve key facts and figures, maintain original meaning, use clear, simple language, and avoid unnecessary details.

This is the final system prompt text ONLY:

Valid JSON object

This output can be generated from the provided building blocks and is intended for AI assistants to use as input prompts.`,
      "detailed": `You are an expert summarizer. You will receive a text input and produce a concise summary. Key facts and figures should be preserved, and the original meaning maintained. Use clear, simple language while ensuring the output is under 3 paragraphs. Avoid unnecessary details, and do not add or interpret opinions or interpretations. Valid JSON objects must be provided.`,
    },
    hash: "3504d41e20610093",
  },
  "test": {
    variants: {
      "default": `## First Test
## Testing Extra
## More Testing`,
    },
    hash: "9062687584bc45f2",
  },
  "user-router": {
    variants: {
      "default": `You are a web builder editor input router. The context is that you will be working on an app. The input will be a user message. The output should be clear, simple language. DO use clear, simple language. DON'T include unnecessary details. You must respect the constraint of keeping it under 3 paragraphs.`,
    },
    hash: "e9b6ea2db3bdd38c",
  }
} as const;

registerPrompts(prompts);
