import "dotenv/config";
import * as fs from "fs";
import { processPrompt, type AIConfig } from "./ai.js";
import { hashState, loadExistingPrompts } from "./cache.js";
import { discoverPrompts, type DiscoveredPrompt } from "./discover.js";

export type GenerateOptions = {
  promptFilenamePattern?: string;
  aiConfig?: AIConfig;
};

async function generate(
  targetDir: string,
  outputPath: string,
  options: GenerateOptions = {},
) {
  const pattern = options.promptFilenamePattern ?? "**/*.prompt.{ts,js}";
  const prompts = await discoverPrompts(targetDir, pattern);

  if (!options.aiConfig) {
    throw new Error("AI config is required in nudge.config.json");
  }

  const existingPrompts = loadExistingPrompts(outputPath);

  console.log(`Processing ${prompts.length} prompt(s)...`);

  const results = await Promise.all(
    prompts.map(async (prompt) => {
      const hash = hashState(prompt.state);
      const existing = existingPrompts[prompt.id];

      let text: string;
      if (existing && existing.hash === hash) {
        console.log(`  ✓ "${prompt.id}" unchanged (cached)`);
        text = existing.text;
      } else {
        console.log(`  → "${prompt.id}" processing with AI...`);
        text = await processPrompt(prompt.state, options.aiConfig!);
      }

      // Escape backticks and ${} for template literal
      const escaped = text
        .replace(/\\/g, "\\\\")
        .replace(/`/g, "\\`")
        .replace(/\$\{/g, "\\${");
      return {
        id: prompt.id,
        entry: `  ${JSON.stringify(prompt.id)}: {\n    text: \`${escaped}\`,\n    hash: ${JSON.stringify(hash)},\n  }`,
        registry: `    ${JSON.stringify(prompt.id)}: true;`,
      };
    }),
  );

  const promptEntries = results.map((r) => r.entry);
  const registryEntries = results.map((r) => r.registry);

  const code = `// This file is auto-generated by @nudge/cli. Do not edit manually.
import { registerPrompts } from "@nudge/core";

declare module "@nudge/core" {
  interface PromptRegistry {
${registryEntries.join("\n")}
  }
}

const prompts = {
${promptEntries.join(",\n")}
} as const;

registerPrompts(prompts);
`;

  // Write TypeScript file
  fs.writeFileSync(outputPath, code, "utf-8");
  console.log(`Generated ${outputPath} with ${prompts.length} prompt(s)`);
}

export { discoverPrompts, generate, type DiscoveredPrompt };
